# SQL 101 - Basic Data Retrieval



By: Martin Arroyo

## Introduction


Now that you have a foundation of database theory under your belt, it's time to learn how to communicate with a database and write queries using SQL! In this notebook, we will focus on teaching you the basics of writing queries against single tables. In 102, we will show you more advanced querying techniques that will enable you to answer more complex, multi-step questions. And in 103, you'll learn how to combine data from multiple tables to enrich your queries - but we will walk before we run.

### About this notebook

All of your queries will be written using preloaded databases that are available only in this notebook. Our "RDBMS" and SQL dialect is called `duckdb`, a new and popular Python library that provides the framework to make our queries possible. You can find [the documentation for `duckdb` here](https://duckdb.org/docs/sql/introduction) - you will want to keep the documentation handy.

`teachdb`, which provides the data that you will be working with, is a Python library written by The Freestack Initiative, a group of COOP alumni who want to empower the community to learn and improve their technical skills by providing materials and resources at low (or no) cost.

## How to use this notebook

First, we'll do a quick tutorial on how to use the notebook with these tools, then we'll dive into your first SQL query!

### **Step 1: Press the play button in the cell below to set up the database and notebook**

You will see a checkmark appear when the database is finished setting up.

In [1]:
%%capture --no-stderr
# @title Press Play { display-mode: "form" }

# This code is used to set up the notebook by installing the libraries we need, configuring extensions to
# make displays for our queries look nice, and connecting to our relational database so that you can write
# queries in code cells using the %%sql magic tag.

# Install `teachdb` if it's not in the system already
%pip install --quiet --upgrade git+https://github.com/freestackinitiative/teachingdb.git
from teachdb import TeachDB
# Set configurations for notebook & load data
db = TeachDB(database=["sales_cogs_opex", "restaurant"])
db.setup_notebook()
con = db.connection
%sql con

# Check out the Freestack Initiative @https://github.com/freestackinitiative

### **Step 2: Run a query**

To run SQL queries against the database, create a new code cell. Then write `%%sql` at the top. This tells the notebook that this cell is being used to query the database. You can write your queries underneath the `%%sql` line by pressing the play button of the cell or selecting the cell and using `CTRL + Shift + Enter` on Windows (`CMD + Shift + Return` on Mac.)

Go ahead and try it by executing the query in the cell below:

In [2]:
%%sql

SELECT *
FROM Dishes
LIMIT 5

,DishID,Name,Description,Price,Type
0,1,Parmesan Deviled Eggs,"These delectable little bites are made with organic eggs, fresh Parmesan, and chopped pine nuts.",8.0,Appetizer
1,2,Artichokes with Garlic Aioli,Our artichokes are brushed with an olive oil and rosemary blend and then broiled to perfection....,9.0,Appetizer
2,3,French Onion Soup,"Caramelized onions slow cooked in a savory broth, topped with sourdough and a provolone cheese ...",7.0,Main
3,4,Mini Cheeseburgers,"These mini cheeseburgers are served on a fresh baked pretzel bun with lettuce, tomato, avocado,...",8.0,Main
4,5,Panko Stuffed Mushrooms,"Large mushroom caps are filled a savory cream cheese, bacon and panko breadcrumb stuffing, topp...",7.0,Appetizer

Now you know how to write your queries in this notebook! Feel free to make as many new cells as you need to experiment with queries. Don't forget to save a copy of the notebook so that you won't lose any of your work. Let's go ahead and learn how to `SELECT` data!

## **Basic Data Retrieval**

**Key Skills/Concepts**

- Write SQL statements to retrieve data from tables.
- Use aliases for clarity in queries.
- Understand how to eliminate duplicate results.

In this first section, we will introduce you to SQL query basics, and you will learn how to write simple queries against a single table. We will also cover how to change the names of items in your query, as well as how to remove duplicate rows.

#### **Scenario**

To make things a bit more interesting, we'll be using a dataset from a fictional restaurant. The queries we write will help you learn more SQL while also learning more about the restaurant and its data. Let's start by looking at the restaurant's menu, which is found in the `Dishes` table.

#### **`SELECT *` - Selecting all columns from a table**

The most basic SQL query you will ever write is one where you simply retrieve all of the data from a single table. In order to create this query, you will need to know two commands: `SELECT` and `FROM`:

- `SELECT`: Used to select all of the specified columns in a table. When we want to select all of the columns in a table, we can use `*` as a shortcut instead of writing all of the column names.
- `FROM`: Specifies the name of the table that you would like to query.

The general form of a query where we ask to see all of the columns and rows in a table is:

```sql
SELECT *
FROM table_name
```

##### **Action Item - Select all columns from a table**

Write a query that shows all of the dishes from the `Dishes` table. The query should include all of the columns from that table as well. Use the general form above to help you structure it:

<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT *
FROM Dishes
```

</details>

In [4]:
%%sql
SELECT *
FROM Dishes

,DishID,Name,Description,Price,Type
0,1,Parmesan Deviled Eggs,"These delectable little bites are made with organic eggs, fresh Parmesan, and chopped pine nuts.",8.00,Appetizer
1,2,Artichokes with Garlic Aioli,Our artichokes are brushed with an olive oil and rosemary blend and then broiled to perfection....,9.00,Appetizer
2,3,French Onion Soup,"Caramelized onions slow cooked in a savory broth, topped with sourdough and a provolone cheese ...",7.00,Main
3,4,Mini Cheeseburgers,"These mini cheeseburgers are served on a fresh baked pretzel bun with lettuce, tomato, avocado,...",8.00,Main
4,5,Panko Stuffed Mushrooms,"Large mushroom caps are filled a savory cream cheese, bacon and panko breadcrumb stuffing, topp...",7.00,Appetizer
5,6,Garden Buffet,"Choose from our fresh local, organically grown ingredients to make a custom salad.",9.99,Main
6,7,House Salad,"Our house salad is made with romaine lettuce and spinach, topped with tomatoes, cucumbers, red ...",7.00,Main
7,8,Chef's Salad,"The chef's salad has cucumber, tomatoes, red onions, mushrooms, hard-boiled eggs, cheese, and h...",9.00,Main
8,9,Quinoa Salmon Salad,"Our quinoa salad is served with quinoa, tomatoes, cucumber, scallions, and smoked salmon. Serve...",9.99,Main
9,10,Classic Burger,"Our classic burger is made with 100% pure angus beef, served with lettuce, tomatoes, onions, pi...",9.99,Main
10,11,Tomato Bruschetta Tortellini,This classic cheese tortellini is cooked in a sundried tomato sauce. Served with bruschetta top...,9.99,Main
11,12,Handcrafted Pizza,"Our thin crust pizzas are made fresh daily and topped with your choices of fresh meats, veggies...",9.99,Main
12,13,Barbecued Tofu Skewers,"Our barbecued skewers include tofu, cherry tomatoes, bell peppers, and zucchini marinated in a ...",9.99,Appetizer
13,14,Fiesta Family Platter,"This platter is perfect for sharing! Enjoy our spicy buffalo wings, traditional nachos, and che...",9.99,Main
14,15,Creme Brulee,Elegantly crafted creamy vanilla custard with a caramelized crunchy layer on top. Served with s...,9.00,Dessert
15,16,Cheesecake,"Our New York Style Cheesecake is rich, smooth, and creamy. Available in various flavors, and wi...",9.00,Dessert
16,17,Chocolate Chip Brownie,A warm chocolate chip brownie served with chocolate or vanilla ice cream and rich chocolate sauce.,6.00,Dessert
17,18,Apple Pie,Made with local granny smith apples to bring you the freshest classic apple pie available.,5.00,Dessert
18,19,Mixed Berry Tart,"Raspberries, blueberries, and strawberries on top of a creamy filling served in a crispy tart.",7.00,Dessert
19,20,Tropical Blue Smoothie,This blueberry mint-based smoothie is refreshing and perfect for any celebration.,6.00,Beverage
20,21,Pomegranate Iced Tea,"Our unique blend of pomegranate juice, black Rooibos, and mint tea creates this light fusion of...",4.00,Beverage
21,22,Cafe Latte,Our house blend of espresso and foamed milk. Can be served with flavored syrups and over ice. ...,6.00,Beverage

#### **`SELECT column1, column2, column3, ...` - Selecting specific columns from a table**

Awesome! You just wrote your first query that retrieved the menu from our database. It seems like they have some really tasty dishes at very reasonable prices. But this is also a lot of information to take in all at once. Right now, **we'd just like to see the name of the dish, the price, and what type it is.** That means we'll need to specify columns that we want!

This leads us to the next general form of a simple select query:

```sql
SELECT column1, column2, column3
FROM table_name
```

##### **Action Item - Select specific columns from a table**

Write a query that shows the `Name`, `Price`, and `Type` of dishes in the `Dishes` table.

<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT Name, Price, Type
FROM Dishes
```
</details>

In [6]:
%%sql
SELECT Name,Price,Type
From Dishes
Limit 6

                           Name  Price       Type
0         Parmesan Deviled Eggs   8.00  Appetizer
1  Artichokes with Garlic Aioli   9.00  Appetizer
2             French Onion Soup   7.00       Main
3            Mini Cheeseburgers   8.00       Main
4       Panko Stuffed Mushrooms   7.00  Appetizer
5                 Garden Buffet   9.99       Main

##### **How to write aliases using the `AS` keyword**

Here's the general form of the query:

```sql
SELECT column1 AS Col1, column2 AS "Column 2"
FROM some_table AS my_table
```

##### **Action Item - Aliases**

Write a query using the same format as the one prior, except rename the `Name` column as `DishName`, the `Price` column as `Cost`, and the `Type` column as `DishType`.

<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT Name AS DishName, Price AS Cost, Type AS DishType
FROM Dishes
```

</details>

In [8]:
%%sql
SELECT Name AS "DishName", Price AS "Cost", Type AS "DishType"
FROM Dishes
Limit 7

                       DishName  Cost   DishType
0         Parmesan Deviled Eggs  8.00  Appetizer
1  Artichokes with Garlic Aioli  9.00  Appetizer
2             French Onion Soup  7.00       Main
3            Mini Cheeseburgers  8.00       Main
4       Panko Stuffed Mushrooms  7.00  Appetizer
5                 Garden Buffet  9.99       Main
6                   House Salad  7.00       Main

##### **How to write a query using `DISTINCT`**

Here is the general query form:

```sql
SELECT DISTINCT column1, column2, column3
FROM some_table
```

##### **Action Item - `DISTINCT` clause**

Using the `Dishes` table, write a query using just the `Type` column that shows the distinct dish types that are available.

<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT DISTINCT Type
FROM Dishes
```

</details>

In [10]:
%%sql
SELECT DISTINCT Type
FROM Dishes

        Type
0       Main
1    Dessert
2  Appetizer
3   Beverage

#### **Basic Data Retrieval - Comprehension Check**

Great job in this section! You learned how to write basic select queries against tables in a database, how to create aliases for column and table names, and how to remove duplicate rows in your query using `DISTINCT`. Let's do some review over what we've learned so far:

**1. What is the difference between a query that uses `SELECT *` and one that uses `SELECT col1, col2`?**
<details>
    <summary>Click here to reveal the answer</summary>
    <p>The query using SELECT * will automatically include all of the columns from the table in the result set. On the other hand, when we use SELECT col1, col2, etc. we are specifying the columns that we want to return.</p>
</details>

**2. What is the clause that we use to create an alias? And is an alias name permanent?**
<details>
    <summary>Click here to reveal the answer</summary>
    <p>We use the AS clause to create an alias. Aliases are not permanent and are generally only for display purposes.</p>
</details>

**3. What does `DISTINCT` do and why should we only use it sparingly?**
<details>
    <summary>Click here to reveal the answer</summary>
    <p>DISTINCT removes duplicate rows in a query result. However, it should be used sparingly because it is a computationally expensive command to run, especially on large data sets.</p>
</details>

## Filtering Data Based On Conditions

**Key Skills/Concepts**
- Implement conditions to filter specific data rows.
- Use text search tools in SQL.
- Apply logical operators to refine query results

#### Using `WHERE` & `HAVING` to filter data

To filter our data, SQL gives us two clauses - `WHERE` and `HAVING`:

**`WHERE`**: Filters data based on a set of one or more specified true/false conditions.
    
*Example:*
```sql
SELECT *
FROM Dishes
WHERE Type='Appetizer'    
```

##### **Action Item 1 - Basic `WHERE` Clause**

Write a query that only shows appetizers from the `Dishes` table. It should only include the name of the dish and the price.

<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT Name, Price
FROM Dishes
WHERE Type='Appetizer'
```

</details>

In [11]:
%%sql
SELECT Name, Price
FROM Dishes
WHERE Type='Appetizer'

                           Name  Price
0         Parmesan Deviled Eggs   8.00
1  Artichokes with Garlic Aioli   9.00
2       Panko Stuffed Mushrooms   7.00
3        Barbecued Tofu Skewers   9.99

##### **Action Item 2 - Basic `WHERE` Clause**

Now write a query that only shows dishes that are considered a main course. Include the name of the dish, its description, and the price in the results.

<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT Name, Description, Price
FROM Dishes
WHERE Type='Main'
```

</details>

In [12]:
%%sql
SELECT Name, Description,Price
From Dishes
WHERE Type ='Main'

,Name,Description,Price
0,French Onion Soup,"Caramelized onions slow cooked in a savory broth, topped with sourdough and a provolone cheese ...",7.00
1,Mini Cheeseburgers,"These mini cheeseburgers are served on a fresh baked pretzel bun with lettuce, tomato, avocado,...",8.00
2,Garden Buffet,"Choose from our fresh local, organically grown ingredients to make a custom salad.",9.99
3,House Salad,"Our house salad is made with romaine lettuce and spinach, topped with tomatoes, cucumbers, red ...",7.00
4,Chef's Salad,"The chef's salad has cucumber, tomatoes, red onions, mushrooms, hard-boiled eggs, cheese, and h...",9.00
5,Quinoa Salmon Salad,"Our quinoa salad is served with quinoa, tomatoes, cucumber, scallions, and smoked salmon. Serve...",9.99
6,Classic Burger,"Our classic burger is made with 100% pure angus beef, served with lettuce, tomatoes, onions, pi...",9.99
7,Tomato Bruschetta Tortellini,This classic cheese tortellini is cooked in a sundried tomato sauce. Served with bruschetta top...,9.99
8,Handcrafted Pizza,"Our thin crust pizzas are made fresh daily and topped with your choices of fresh meats, veggies...",9.99
9,Fiesta Family Platter,"This platter is perfect for sharing! Enjoy our spicy buffalo wings, traditional nachos, and che...",9.99

### **Comparison and Logical Operators**

#### **Comparison Operators**: Used to compare one value to another when filtering.

![Conditional Operators in SQL](https://github.com/freestackinitiative/coop_sql_notebooks/blob/2.0/assets/comparison-operators.png?raw=1)

#### **Logical Operators**: Used to compare two or more conditions when filtering.

![Logical Operators in SQL](https://github.com/freestackinitiative/coop_sql_notebooks/blob/2.0/assets/logical-operators.png?raw=1)

>**Extra Context: <em>Boolean Logic</em>**
>
> Boolean logic is a system of thought based on "binary" choices: true or false, yes or no, 1 or 0. It's like a light switch that can either be on (true) or off (false), and it's used in computing to make decisions based on these binary conditions. These are the same conditions used when filtering data. It is used extensively in coding and analytics, so it is crucial to understand at least the basics. [Here is a great article](https://www.codecademy.com/resources/blog/what-is-boolean-logic/) that breaks the concept down nicely.

Let's work through some examples together.

---

### **Lab 1 - Queries with Comparison and Logical Operators**

In this first lab, you will work through examples of how to use both comparison and logical operators in your queries. You will learn:

- How to use comparison operators like `<`, `>`, `>=`, and `<=` to filter results based on a condition
- How to use logical operators like `AND` & `OR` to combine multiple conditions into a filter
- When and how to use the `BETWEEN` and `IN` logical operators to make your queries more readable

**Instructions**

Read through the material and examples provided. Cells marked as **Action Item** will prompt you to write a query. You should write the requested query in the cell following that **Action Item**.

#### **Comparison Operator Examples**

Let's start getting familiar with some of the comparison operators. These are really useful when we want to filter by ranges of numeric values.

##### **Example #1 - Less Than (`<`)**

For example, let's say we wanted to **find all of the dishes that cost less than \$6.00 at our restaurant**. We can do that with the following query:

```sql
SELECT *
FROM Dishes
WHERE Price < 6.0
```

This filter is saying, **<em>"Only return results where the price is less than $6."</em>** Note that we are using `6.0` as the value because the data in the `Price` column is stored as a decimal number. The values that you use in filters need to match how they are stored in the table you are querying. When this query runs, any rows where the condition `Price < 6.0` is `true` are kept and all other rows (where the condition evaluates to `false`) are discarded from our results.

##### **Example #2 - Greater Than or Equal To (`>=`)**

Let's do another example. Now we want to **see what dishes on the menu are $7 or more**. To find them, we could use the following query:

```sql
SELECT *
FROM Dishes
WHERE Price >= 7.0
```

As you might expect, this filter is saying, **<em>"Show me the dishes that cost $7 or more."</em>**

##### **Example #3 - Not equal to (`<>`)**

For our next example, we'll **remove any dishes from our results that cost exactly $9.**

```sql
SELECT *
FROM Dishes
WHERE Price <> 9.0
```

##### **Action Item 1 - Comparison Operators**

Write a query that **only returns dishes that cost $5 or more from the `Dishes` table.** Show the name, type, and description of the dish only.

<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT Name, Type, Description
FROM Dishes
WHERE Price >=5.0

```

</details>

In [13]:
%%sql
SELECT *
FROM Dishes
Where Price >=5.0

,DishID,Name,Description,Price,Type
0,1,Parmesan Deviled Eggs,"These delectable little bites are made with organic eggs, fresh Parmesan, and chopped pine nuts.",8.00,Appetizer
1,2,Artichokes with Garlic Aioli,Our artichokes are brushed with an olive oil and rosemary blend and then broiled to perfection....,9.00,Appetizer
2,3,French Onion Soup,"Caramelized onions slow cooked in a savory broth, topped with sourdough and a provolone cheese ...",7.00,Main
3,4,Mini Cheeseburgers,"These mini cheeseburgers are served on a fresh baked pretzel bun with lettuce, tomato, avocado,...",8.00,Main
4,5,Panko Stuffed Mushrooms,"Large mushroom caps are filled a savory cream cheese, bacon and panko breadcrumb stuffing, topp...",7.00,Appetizer
5,6,Garden Buffet,"Choose from our fresh local, organically grown ingredients to make a custom salad.",9.99,Main
6,7,House Salad,"Our house salad is made with romaine lettuce and spinach, topped with tomatoes, cucumbers, red ...",7.00,Main
7,8,Chef's Salad,"The chef's salad has cucumber, tomatoes, red onions, mushrooms, hard-boiled eggs, cheese, and h...",9.00,Main
8,9,Quinoa Salmon Salad,"Our quinoa salad is served with quinoa, tomatoes, cucumber, scallions, and smoked salmon. Serve...",9.99,Main
9,10,Classic Burger,"Our classic burger is made with 100% pure angus beef, served with lettuce, tomatoes, onions, pi...",9.99,Main
10,11,Tomato Bruschetta Tortellini,This classic cheese tortellini is cooked in a sundried tomato sauce. Served with bruschetta top...,9.99,Main
11,12,Handcrafted Pizza,"Our thin crust pizzas are made fresh daily and topped with your choices of fresh meats, veggies...",9.99,Main
12,13,Barbecued Tofu Skewers,"Our barbecued skewers include tofu, cherry tomatoes, bell peppers, and zucchini marinated in a ...",9.99,Appetizer
13,14,Fiesta Family Platter,"This platter is perfect for sharing! Enjoy our spicy buffalo wings, traditional nachos, and che...",9.99,Main
14,15,Creme Brulee,Elegantly crafted creamy vanilla custard with a caramelized crunchy layer on top. Served with s...,9.00,Dessert
15,16,Cheesecake,"Our New York Style Cheesecake is rich, smooth, and creamy. Available in various flavors, and wi...",9.00,Dessert
16,17,Chocolate Chip Brownie,A warm chocolate chip brownie served with chocolate or vanilla ice cream and rich chocolate sauce.,6.00,Dessert
17,18,Apple Pie,Made with local granny smith apples to bring you the freshest classic apple pie available.,5.00,Dessert
18,19,Mixed Berry Tart,"Raspberries, blueberries, and strawberries on top of a creamy filling served in a crispy tart.",7.00,Dessert
19,20,Tropical Blue Smoothie,This blueberry mint-based smoothie is refreshing and perfect for any celebration.,6.00,Beverage
20,22,Cafe Latte,Our house blend of espresso and foamed milk. Can be served with flavored syrups and over ice. ...,6.00,Beverage

##### **Action Item 2 - Comparison Operators**

Write a query that returns **all of the dishes in the `Dishes` table that cost less than $5.** Show the name of the dish, its description, and the type of dish only.

<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT Name, Description, Type
FROM Dishes
WHERE Price < 5.0
```

</details>

In [14]:
%%sql
SELECT Name, Description, Type
FROM Dishes
WHERE Price <=5.0

,Name,Description,Type
0,Apple Pie,Made with local granny smith apples to bring you the freshest classic apple pie available.,Dessert
1,Pomegranate Iced Tea,"Our unique blend of pomegranate juice, black Rooibos, and mint tea creates this light fusion of...",Beverage

#### **Logical Operator Examples**

Now that we understand how to use conditional operators, let's look more closely at filters with multiple conditions. As mentioned earlier, we use logical operators to evaluate the results of two or more conditions together to decide whether or not to include a row in the result.

Let's assume that the average price of an appetizer at restaurants similar to ours is \$7. If we want to see appetizers on our menu that cost more than average, we need to specify two conditions:  
-  `Type='Appetizer'` and
-  `Price > 7.0`.

Here, both conditions (`Type='Appetizer'` **AND** `Price > 7.0`) *must* be true. Let's put that into a query:

```sql
SELECT *
FROM Dishes
WHERE Type='Appetizer' AND Price > 7.0
```

##### **Action Item 1 - Logical Operators**

Copy the query above into the cell below, run it, and check the results. Do we have appetizers that cost more than the average? If yes, which ones are they?

<details>
<summary>Click here to reveal answer</summary>
<p>Yes, we do. The appetizers that cost more than the average are the Parmesan Deviled Eggs, Artichokes with Garlic Aioli, and the Barbecued Tofu Skewers</p>
</details>

In [15]:
%%sql
SELECT *
FROM Dishes
WHERE Type='Appetizer' AND Price > 7.0

,DishID,Name,Description,Price,Type
0,1,Parmesan Deviled Eggs,"These delectable little bites are made with organic eggs, fresh Parmesan, and chopped pine nuts.",8.00,Appetizer
1,2,Artichokes with Garlic Aioli,Our artichokes are brushed with an olive oil and rosemary blend and then broiled to perfection....,9.00,Appetizer
2,13,Barbecued Tofu Skewers,"Our barbecued skewers include tofu, cherry tomatoes, bell peppers, and zucchini marinated in a ...",9.99,Appetizer

##### **Action Item 2 - Logical Operators**

Take the same query from the last example, change `AND` to `OR`, and run it. Note the difference in the results between the two queries. Why did that happen?

<details>
    <summary>Click here to reveal the answer</summary>
    <p>When we changed from <strong>AND</strong> to <strong>OR</strong>, the logic of our filter changed. Instead of saying <em>"show me only appetizers that cost more than $7"</em>, replacing <strong>AND</strong> with <strong>OR</strong> changes that to <em>"show me all of the appetizers on the menu or any dishes that cost more than $7."</em></p>
</details>

In [16]:
%%sql
SELECT *
FROM Dishes
WHERE Type='Appetizer' OR Price > 7.0

,DishID,Name,Description,Price,Type
0,1,Parmesan Deviled Eggs,"These delectable little bites are made with organic eggs, fresh Parmesan, and chopped pine nuts.",8.00,Appetizer
1,2,Artichokes with Garlic Aioli,Our artichokes are brushed with an olive oil and rosemary blend and then broiled to perfection....,9.00,Appetizer
2,4,Mini Cheeseburgers,"These mini cheeseburgers are served on a fresh baked pretzel bun with lettuce, tomato, avocado,...",8.00,Main
3,5,Panko Stuffed Mushrooms,"Large mushroom caps are filled a savory cream cheese, bacon and panko breadcrumb stuffing, topp...",7.00,Appetizer
4,6,Garden Buffet,"Choose from our fresh local, organically grown ingredients to make a custom salad.",9.99,Main
5,8,Chef's Salad,"The chef's salad has cucumber, tomatoes, red onions, mushrooms, hard-boiled eggs, cheese, and h...",9.00,Main
6,9,Quinoa Salmon Salad,"Our quinoa salad is served with quinoa, tomatoes, cucumber, scallions, and smoked salmon. Serve...",9.99,Main
7,10,Classic Burger,"Our classic burger is made with 100% pure angus beef, served with lettuce, tomatoes, onions, pi...",9.99,Main
8,11,Tomato Bruschetta Tortellini,This classic cheese tortellini is cooked in a sundried tomato sauce. Served with bruschetta top...,9.99,Main
9,12,Handcrafted Pizza,"Our thin crust pizzas are made fresh daily and topped with your choices of fresh meats, veggies...",9.99,Main
10,13,Barbecued Tofu Skewers,"Our barbecued skewers include tofu, cherry tomatoes, bell peppers, and zucchini marinated in a ...",9.99,Appetizer
11,14,Fiesta Family Platter,"This platter is perfect for sharing! Enjoy our spicy buffalo wings, traditional nachos, and che...",9.99,Main
12,15,Creme Brulee,Elegantly crafted creamy vanilla custard with a caramelized crunchy layer on top. Served with s...,9.00,Dessert
13,16,Cheesecake,"Our New York Style Cheesecake is rich, smooth, and creamy. Available in various flavors, and wi...",9.00,Dessert

#### **Logical Operators (continued) - Range conditions: Using `IN` and `BETWEEN`**

Along with `AND` and `OR`, there are several other very useful logical operators - particularly those that let us check if a value is within a range of other values.

##### **Using the `IN` clause to find values within a range of other values**

##### **Example without `IN`**

**Let's find all of the appetizers or main course meals that costs $8 or more.** We'll translate that into the following query:

```sql
SELECT *
FROM Dishes
WHERE Type='Appetizer' OR Type='Main' AND Price >= 8.0
```

This query returns the results that we expected - all of the appetizer or main course dishes that cost $8 or more. But what if we wanted to check for additional types in our condition? We could just keep adding `OR Type='Some Other Type'` statements to our filter. But that can get confusing to work with and difficult to debug as the list grows longer, though.

##### **Example using `IN`**

**Let's see how we can use the `IN` operator to get the same results:**

```sql
SELECT *
FROM Dishes
WHERE Type IN ('Appetizer', 'Main') AND Price >= 8.0
```

##### **Breakdown - How `IN` works**

Both queries return the same results. This filter is saying the same thing as the one before, just in a slightly different way.

The `IN` clause lets us check if a value is `IN` a list of values that we specify surrounded by parentheses `()`. In this case, we specified the appetizer and main course dish types as the list of possible values. Our query then checks the rows in the `Dishes` table and checks if the `Type` is in that list.

##### **Using `BETWEEN` to find if a value falls within a range of other (like) values**

What do we do when we want to check if value in our data falls within a range of like values? SQL gives us a couple of different tools to use to solve this problem. We'll explain two methods you can use and why you might choose one over the other.

##### **Example without using `BETWEEN`**

**Let's say we want to find all of the dishes on our menu that cost between \$8 and $10.** We can write that query with just conditional operators. Here's how that would look:

```sql
SELECT *
FROM Dishes
WHERE Price >= 8.0 AND Price <= 10.0
```

This will show us all of the dishes between \$8 and $10 dollars. But SQL offers us a more readable way to write this using the `BETWEEN` operator.

`BETWEEN` checks if some value is >= a minimum value and <= a maximum value.

##### **Example using `BETWEEN`**

**Here is what our query looks like rewritten using `BETWEEN`**:

```sql
SELECT *
FROM Dishes
WHERE Price BETWEEN 8.0 AND 10.0
```

##### **Breakdown - Using `BETWEEN`**

Both queries give the same result. Using different syntax can yield the same query results but also improve readability. Enhanced readability is crucial for team collaboration and for understanding your own work when revisiting it later.

##### **Action Item - Using `BETWEEN` and `IN`**

Write a query that finds all desserts and beverages that cost between \$3 and $8 dollars. Your results should show the name of the dish, the price, and the description.

<details>
    <summary>Click here to reveal the answer</summary>

```sql
SELECT Name, Price, Description
FROM Dishes
WHERE Type IN ('Dessert', 'Beverage') AND Price BETWEEN 3.0 AND 8.0
```
    
</details>

In [17]:
%%sql
SELECT Type ='Desserts' AND Type ='beverages'
FROM Dishes
WHERE Price BETWEEN 8.0 AND 10.0

    (("Type" = 'Desserts') AND ("Type" = 'beverages'))
0                                                False
1                                                False
2                                                False
3                                                False
4                                                False
5                                                False
6                                                False
7                                                False
8                                                False
9                                                False
10                                               False
11                                               False
12                                               False

**You have reached the end of Lab 1. Great work!**

---

### **`LIKE` and `%` - Basic Text Pattern Matching Filters**

When we have text data, we may want to filter it by searching for particular words, phrases, or patterns in that text. Pattern matching is a powerful feature in SQL that allows us to search for patterns within text data. In this section, we'll teach you some basic patterns used for finding data that matches some word or phrase.

#### **Basic Pattern #1 - Finding a word or phrase within text**

Let's suppose that **we want to find any dishes on the menu that have onions in them.** To do that, we can use **pattern matching with the `LIKE` operator with `%`.**

**The `%` is known as a wildcard operator**. This means that it can be used to match zero to many characters in a given string. By putting a copy of this wildcard operator on each side of a search term, we are saying, **<em>"Check the text to see if this search term is in it somewhere."</em>**

Here is how the query looks:

```sql
SELECT *
FROM Dishes
WHERE Description LIKE '%onion%'
```

##### **Basic Pattern #1 - Breakdown**

Ok, now let's break down what's happening in this query. First, we chose to use the `Description` column because it has text data that describes ingredients in each dish. Next, we use the `LIKE` operator to tell SQL that we want to find a pattern in the `Description` column that looks like the one we gave it. After that, we see `%onion%`, which is our search term and pattern. But why are we using the wildcard operator (`%`) on each side?

Our search term and pattern - `%onion%` - matches the following sentence because the word "onion" is in it:

<em>"Caramelized [**onion**]s slow cooked in a savory broth, topped with sourdough and a provolone cheese blend. Served with sourdough bread."</em>

>`Pro-Tip:` Trying to find a word or phrase within some text is a very common search pattern. This is worth memorizing.

#### **Basic Pattern #2 - Finding text that starts or ends with a character, word, or phrase using `LIKE` with `%`**

Another common search pattern is trying to filter text that either starts or ends with a particular character, word, or phrase. As an example, let's say we wanted to find all of the dishes that start with the letter 'C' or end with the letter 'a'. Here is what that query would look like:

```sql
SELECT *
FROM Dishes
WHERE Name LIKE 'C%' OR Name LIKE '%a'
```

And here are some of the results from the query. The `[]` brackets are used to indicate how the pattern matched to the result:

| Name              |
|-------------------|
| [**C**]heesecake        |
| Handcrafted Pizz[**a**] |

##### **Basic Pattern #2 - Breakdown**

The `LIKE 'C%'` part of our pattern matches with `Cheesecake`, since it is saying, **<em>"Show me any text that starts with a capital 'C'."</em>** And the `LIKE '%a'` part of the pattern matches `Handcrafted Pizza` because it says, **<em>"Show me any text that ends with a lowercase 'a'."</em>** In both cases, we are taking advantage of the fact that `%` matches to 0 or more characters to match all the characters except the first or the last, respectively.

#### **Basic Pattern #3 - Using the Single Character Wildcard ( `_` )**

The underscore character ( `_` ) is a wildcard just like `%`. The only difference is that `_` only matches any single character.  

The following query:

```sql
SELECT *
FROM table
WHERE column LIKE 'COOP_';
```

will filter for and match any strings that are like the following:

| Name  |
|-------|
| COOP_ |
| COOP1 |
| COOP2 |

but it will not match strings like **"COOP12"** or **"COOP12345"**.

##### **Action Item - Basic Pattern Matching**

Write a query to **find all of the dishes on the menu that have `cheese` in them.** Show the name of the dish, the price, and the type only.

<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT Name, Price, Type
FROM Dishes
WHERE Description LIKE '%cheese%'
```

</details>

In [26]:
%%sql
SELECT Name, Price, Type
FROM Dishes
WHERE Description LIKE '%cheese%'

                           Name  Price       Type
0             French Onion Soup   7.00       Main
1            Mini Cheeseburgers   8.00       Main
2       Panko Stuffed Mushrooms   7.00  Appetizer
3                  Chef's Salad   9.00       Main
4                Classic Burger   9.99       Main
5  Tomato Bruschetta Tortellini   9.99       Main
6             Handcrafted Pizza   9.99       Main
7         Fiesta Family Platter   9.99       Main

### **Filtering Data Based on Conditions - Comprehension Check**

Great work completing this section! You learned how to write more complex queries by using filters with conditions. You even did some basic text pattern matching to help you find patterns in text data. Let's do some review over what we've learned so far:

**1. Why is filtering data important?**
<details>
    <summary>Click here to reveal the answer</summary>
    <p>Filtering allows us to view only relevant data in our results. It also makes our queries more efficient by decreasing the amount of data that we need to pull in. </p>
</details>

**2. What is the difference between `WHERE` and `HAVING`?**
<details>
    <summary>Click here to reveal the answer</summary>
    <p>We use the `WHERE` clause whenever we want to filter rows. We use `HAVING` to filter by the results of an aggregate function.</p>
</details>

**3. Which operators do we use to compare two or more conditions in a filter?**
<details>
    <summary>Click here to reveal the answer</summary>
    <p>`AND`, `OR`.</p>
</details>

**4. What is the difference between the `%` and the `_` wildcards?**
<details>
    <summary>Click here to reveal the answer</summary>
    <p>The <em>%</em> wildcard matches zero or more characters in a text string, and the <em>_</em> wildcard matches only one character in a text string.</p>
</details>

**5. In the cell below, write a query that finds any dishes that have cheese in them and cost between $7 and $10. Your query should return the name of the dish, the price, and the description.**
<details>
    <summary>Click here to reveal the answer</summary>

    ```sql
    SELECT Name, Price, Description
    FROM Dishes
    WHERE Description LIKE '%cheese%' AND Price BETWEEN 7.0 AND 10.0
    ```

</details>

In [28]:
%%sql
SELECT Name, Price, Type
FROM Dishes
WHERE Description LIKE '%cheese%' AND price BETWEEN 7.0 AND 10.0

                           Name  Price       Type
0             French Onion Soup   7.00       Main
1            Mini Cheeseburgers   8.00       Main
2       Panko Stuffed Mushrooms   7.00  Appetizer
3                  Chef's Salad   9.00       Main
4                Classic Burger   9.99       Main
5  Tomato Bruschetta Tortellini   9.99       Main
6             Handcrafted Pizza   9.99       Main
7         Fiesta Family Platter   9.99       Main

from matplotlib import pyplot as plt
_df_0['Price'].plot(kind='hist', bins=20, title='Price')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby('Name').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby('Type').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['Price'].plot(kind='line', figsize=(8, 4), title='Price')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Type'].value_counts()
    for x_label, grp in _df_4.groupby('Name')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Name')
_ = plt.ylabel('Type')

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_5['Name'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_5, x='Price', y='Name', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_6['Type'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_6, x='Price', y='Type', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

## Data Aggregation and Ordering Basics

**Key Skills/Concepts**
- Aggregate data to derive analytical insights.
- Sort query results.

### **`COUNT`, `SUM`, `AVG`, `MIN`, `MAX` - Basic Aggregate Functions**

So far, you have learned how to write queries for basic data retrieval and how to filter your queries to get targeted results. You have a developed foundation in querying data and getting the results you want from a single table. But, more often than not, simply obtaining query results from a table is only the beginning of your analysis. We need a way to summarize what we are seeing in the data without examining each individual row. That is what **data aggregration is - the process of gathering and summarizing large sets of data to produce a single, consolidated result, like calculating the average grade of students in a class.**

##### **How to write a query to aggregate data across an entire table**

To summarize data across the entire table, our queries use the following general form:

```sql
SELECT AGGREGATE_FUNCTION(Column1)
FROM some_table
```

---



### **Lab 2: Basic Aggregation with `COUNT`, `MIN`, `MAX`, and `AVG`**

In the following lab, you will practice writing basic aggregate functions across an entire table. You will learn:

- How to `COUNT` the total number of values in columns and the total number of rows in a table
- How to apply the `MIN`, `MAX`, and `AVG` aggregate functions to a query

#### **Using `COUNT` to find the total number of values in a column and the total number of rows in a table**

##### **Finding the total number of values in a column:**

Each aggregate function typically takes in a single column as a parameter. It then performs an aggregate operation over the values in that column. For a more realistic example, let's simply count the number of dishes on the menu using the `COUNT` function:

```sql
SELECT COUNT(Name)
FROM Dishes
```

`Result:`

| COUNT |
|-------|
| 22    |

##### **Breakdown - Total number of values in a column**

The query here is asking the database to "Count the total number of dishes in the `Dishes` table and give us the result." When we pass a column name to the `COUNT` function, SQL will then count each **<em>non-null</em>** value in that column.

>**Extra Context: <em>NULL values</em>**
>
> `NULL` values in data indicate either a missing or undefined value. This can be caused by data entry errors or can even be intentional. In discussion, you may hear people say "non-null" value, which simply means that a value is present and not `NULL`. You should be aware of `NULL` values that may appear in your data set.

##### **Finding the total number of rows in a table**

The query to find the total number of rows in any table takes the following general form:

```sql
SELECT COUNT(*)
FROM table_name
```

By using the `*` wildcard as a parameter to the `COUNT` function, we are saying, **<em>"count ALL of the rows in the table whether or not there are null values."</em>** To demonstrate the difference between `COUNT(*)` and `COUNT(Name)`, we will insert a null record into the `Dishes` table and take both counts.

Run the query in the cell below:

In [30]:
%%sql
INSERT INTO Dishes (DishID, Name, Description, Price, Type) VALUES (NULL, NULL, NULL, NULL, NULL);

SELECT COUNT(*) AS total_rows, COUNT(Name) AS total_dishes
FROM Dishes;

   total_rows  total_dishes
0          23            22

As you can see, `COUNT(*)` counted all of the rows in the table, while `COUNT(Name)` only counted the rows where there is a dish, skipping the one(s) that have a null value. This is a common pattern to use when exploring data with SQL, as you can now get a sense of which columns in your data have null values as well as how many rows are in a table.

> **Pro-Tip: It is worth memorizing this pattern as you will use it quite often when doing exploratory analysis in SQL. Understanding the counts of things in your data is a crucial part of understanding your data in general.**

Now let's run the cell below to clean up any `NULL` rows generated from the previous example:

In [29]:
%%sql

DELETE FROM Dishes WHERE DishID IS NULL;

   Count
0      0

##### **Action Item - Using `COUNT`**

Write a query that counts the total number of rows in the `Customers` table. Use `total_rows` as an alias for the result column.

*Note: There are no null values in this table, so the total number of rows is also the total number of customers.*

How many customers are in the `Customers` table?

<details>
    <summary>Click here to reveal the answer</summary>

    Here is the query:

```sql
SELECT COUNT(*) AS total_rows
FROM Customers
```

    The results should show that we have 100 customers.
</details>

In [31]:
%%sql
SELECT COUNT (*) AS total_rows
FROM Customers

   total_rows
0         100

#### **Using `MIN`, `MAX`, `AVG`, and `SUM` to summarize data in a table**

Recall the general form for using an aggregate function across all values in a table is:

```sql
SELECT AGGREGATE_FUNCTION(Column1)
FROM some_table
```

We can simply swap `AGGREGATE_FUNCTION` for any one of the following aggregate functions `MIN`, `MAX`, `AVG`, and `SUM` to summarize data based on what we are looking for.

For example, **let's find the lowest priced dish on the menu**:
```sql
SELECT MIN(Price) AS LowPrice
FROM Dishes
```
`Returns:`

| LowPrice |
|----------|
| 4.0      |

##### **Action Item 1 - Using `MIN`, `MAX`, and `AVG` on a table**

Write a query to find the highest priced dish on the menu using `MAX`. Name the result column `HighestPrice`.

<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT MAX(Price) AS HighestPrice
FROM Dishes
```

</details>

In [32]:
%%sql
SELECT MAX(Price) AS HighestPrice
From Dishes

   HighestPrice
0          9.99

##### **Action Item 2 - Using `MIN`, `MAX`, and `AVG` on a table**

Write a query to find the average price of a dish on the menu using `AVG`. Name the result column `MeanPrice`.

<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT AVG(Price) AS MeanPrice
FROM Dishes
```

</details>

In [33]:
%%sql
SELECT AVG(Price) AS MeanPrice
From Dishes

   MeanPrice
0   8.042273

**You've reached the end of Lab 2! Great work!**

---

### **`GROUP BY` - Aggregating data by categories in a table**

Up to this point, we have been summarizing our data across all of the values in the entire table. These kinds of metrics are useful, but they only tell part of the picture. What if we want to drill even deeper into the data and understand the patterns that are happening within a table?

#### How does `GROUP BY` work?

`GROUP BY` lets us aggregate our data by categories that already exist in a table. Another way to think about `GROUP BY` is to view it as saying, **<em>"Summarize my data by the categories I specify."</em>** In the `Dishes` table, we have a column called `Type` that tells us the category of a dish (`Appetizer`, `Main`, `Dessert`, `Beverage`). Using `GROUP BY` will allow us to answer questions about each of these categories, like **<em>"How many beverages are offered on the menu?"</em>** or **<em>"What's the average price of a main course?"</em>**

#### **An example using `GROUP BY`**

We'll write a query to answer the question, **<em>"How many dishes are there in each category (Appetizers, Main Courses, Desserts, and Beverages)?"**:</em>

```sql
SELECT Type, COUNT(Type) AS total_dishes
FROM Dishes
GROUP BY Type
```
`Results:`

| Type      | TotalDishes |
|-----------|-------------|
| Appetizer | 4           |
| Main      | 10          |
| Dessert   | 5           |
| Beverage  | 3           |

##### **Action Item 1 - Using `GROUP BY`**

Write a query to find the highest price for dish in each `Type` from the `Dishes` table. Your result should match the following output:

`Expected Output:`

| Type      | MaxPrice |
|-----------|----------|
| Appetizer | 9.99     |
| Main      | 9.99     |
| Dessert   | 9.00     |
| Beverage  | 6.00     |

<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT Type, MAX(Price) AS MaxPrice
FROM Dishes
GROUP BY Type
```

</details>

In [34]:
%%sql
SELECT Type, MAX(Type) AS MaxPrice
FROM Dishes
GROUP BY TYPE

        Type   MaxPrice
0       Main       Main
1    Dessert    Dessert
2   Beverage   Beverage
3       None       None
4  Appetizer  Appetizer

##### **Action Item 2 - Using `GROUP BY`**

Write a query to find the average price for a dish in each `Type` from the `Dishes` table. Your result should match the following output:

`Expected Output:`

| Type      | MeanPrice |
|-----------|-----------|
| Appetizer | 8.497500  |
| Main      | 9.094000  |
| Dessert   | 7.200000  |
| Beverage  | 5.333333  |

<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT Type, AVG(Price) AS MeanPrice
FROM Dishes
GROUP BY Type
```

</details>

In [38]:
%%sql
SELECT Type, AVG(Price) AS MeanPrice
FROM Dishes
GROUP BY Type

        Type  MeanPrice
0       Main   9.094000
1    Dessert   7.200000
2       None        NaN
3  Appetizer   8.497500
4   Beverage   5.333333

##### **Action Item 3 - Using `GROUP BY`**

Write a single query that returns the following information for each `Type` from the `Dishes` table:
- The average price of a dish
- The minimum price of a dish
- The maximum price of a dish

Your result should match the following output:

`Expected Output:`

| Type      | MeanPrice | MinPrice | MaxPrice |
|-----------|-----------|----------|----------|
| Appetizer | 8.497500  | 7.00     | 9.99     |
| Main      | 9.094000  | 7.00     | 9.99     |
| Dessert   | 7.200000  | 5.00     | 9.00     |
| Beverage  | 5.333333  | 4.00     | 6.00     |

<br/>
<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT Type, AVG(Price) AS MeanPrice, MIN(Price) AS MinPrice, MAX(Price) AS MaxPrice
FROM Dishes
GROUP BY Type
```

</details>

In [43]:
%%sql
SELECT Type, AVG(Price) AS MeanPrice, MAX(Price) AS MaxPrice, MIN(Price) AS MinPrice
FROM Dishes
GROUP BY Type

        Type  MeanPrice  MaxPrice  MinPrice
0       Main   9.094000      9.99       7.0
1    Dessert   7.200000      9.00       5.0
2       None        NaN       NaN       NaN
3  Appetizer   8.497500      9.99       7.0
4   Beverage   5.333333      6.00       4.0

### **`HAVING` - Filtering data using the result of aggregate functions**

Earlier in the class, we mentioned the `HAVING` filter was used for filtering our data using the result of aggregate functions. Now that you know more about how aggregate functions work, we'll show you how to apply filters using their results.

##### **Example - Using the `HAVING` filter**

Here's how to find only the states where 5 or more customers come from using the `Customers` table:

```sql
SELECT State, COUNT(State) AS TotalCustomers
FROM Customers
GROUP BY State
HAVING COUNT(State) >= 5
```

`Result:`

| State | TotalCustomers |
|-------|----------------|
| CA    | 16             |
| FL    | 7              |
| DC    | 7              |
| VA    | 8              |
| TX    | 9              |
| NY    | 7              |

##### **Action Item - Using the `HAVING` filter**

Write a query that finds all the cities in the `Customers` table that have more than 2 customers.

`Expected Output:`

| City          | TotalCustomers |
|---------------|----------------|
| Washington    | 7              |
| New York City | 4              |
| El Paso       | 3              |
| Oklahoma City | 3              |

<br/>
<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT City, COUNT(City) AS TotalCustomers
FROM Customers
GROUP BY City
HAVING COUNT(City) > 2
```

</details>

In [44]:
%%sql
SELECT City, COUNT(City) AS TotalCustomers
FROM Customers
GROUP BY City
HAVING COUNT(City) >= 2

             City  TotalCustomers
0        Columbus               2
1      Washington               7
2    Philadelphia               2
3      Sacramento               2
4      Des Moines               2
5   Oklahoma City               3
6     Los Angeles               2
7      Long Beach               2
8    Grand Rapids               2
9     San Antonio               2
10  New York City               4
11        El Paso               3
12  San Francisco               2

### **`ORDER BY`, `LIMIT`, and `OFFSET` - Ordering query results**

So far, you have learned how to select, filter, and aggregate data in a single table using SQL. To round out the basics, we will teach you how to order and limit your query results.

---

### **Lab 3 - Using `ORDER BY`, `LIMIT`, and `OFFSET`**

In this final lab, you will work on another fundamental SQL skill: sorting and limiting your data.

After completing this lab, you will:

- Know how to use `ORDER BY` to sort your data in ascending or descending order
- Understand how to use `LIMIT` and `OFFSET` to choose how much data your query returns and from what rows

#### **`ORDER BY` - Ordering query results in ascending or descending order**

When writing our queries earlier, we didn't consider how we might want to order our output. Let's take the example of finding the number of dishes in each type. Here's the query and the results:

```sql
SELECT Type, COUNT(Type) AS TotalDishes
FROM Dishes
GROUP BY Type
```
`Returns:`

| Type      | TotalDishes |
|-----------|-------------|
| Appetizer | 4           |
| Main      | 10          |
| Dessert   | 5           |
| Beverage  | 3           |

##### **Ordering data in ascending order - least to greatest**

Now this query gets us the results we asked for. But what if we want to see the `Type` with the most dishes, or show the `Type` of dish in order from least dishes to most? To do that, SQL provides us with the `ORDER BY` clause.

`ORDER BY` will sort your data by one or more columns that you specify.

##### **Example - Using `ORDER BY` to sort data in ascending order**

Let's order the dishes by their total count from least to greatest:
```sql
SELECT Type, COUNT(Type) AS TotalDishes
FROM Dishes
GROUP BY Type
ORDER BY TotalDishes
```
`Returns:`

| Type      | TotalDishes |
|-----------|-------------|
| Beverage  | 3           |
| Appetizer | 4           |
| Dessert   | 5           |
| Main      | 10          |

##### **Breakdown - Ordering data in ascending or descending order**

We've already seen most of the query already, so we're only going to focus on the last line - `ORDER BY TotalDishes`. This line is saying, **<em>"Take my query results and order them, from least to greatest, based on the values in `TotalDishes`."</em>** By default, `ORDER BY` assumes you mean that you want to order your results in ascending order (least to greatest.)

However, you can also specify that you want your results ordered in descending order (greatest to least.) To specify your sort order, you can add the `DESC` keyword after a column in `ORDER BY` to tell SQL, **<em>"Order my results based on the values in this column in descending order."</em>** While ascending is the default order, you can explicitly specify it as the sort order using the `ASC` keyword.

##### **Ordering data in descending order - greatest to least**

Let's use the same query, except we'll change the sort order from ascending to descending:

```sql
SELECT Type, COUNT(Type) AS TotalDishes
FROM Dishes
GROUP BY Type
ORDER BY TotalDishes DESC
```
`Returns:`

| Type      | TotalDishes |
|-----------|-------------|
| Main      | 10          |
| Dessert   | 5           |
| Appetizer | 4           |
| Beverage  | 3           |

##### **Action Item - Using `ORDER BY`**

Write a query to find the average price for dish in each `Type` from the `Dishes` table. Order your results by the `MeanPrice` from greatest price to the least. Your result should match the following output:

| Type      | MeanPrice |
|-----------|-----------|
| Main      | 9.094000  |
| Dessert   | 7.200000  |
| Beverage  | 5.333333  |
| Appetizer | 8.497500  |

<br/>
<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT Type, AVG(Price) AS MeanPrice
FROM Dishes
GROUP BY Type
ORDER BY Type DESC
```

</details>

In [54]:
%%sql
SELECT Type, AVG(Price) AS MeanPrice
FROM Dishes
GROUP BY Type
ORDER BY Type DESC

        Type  MeanPrice
0       Main   9.094000
1    Dessert   7.200000
2   Beverage   5.333333
3  Appetizer   8.497500
4       None        NaN

#### **`LIMIT` and `OFFSET` - Limiting your query results**

Very often, when we're doing exploratory work in a database, we want to see what the data in a table looks like, but we don't need to see all of it. It's more useful and efficient to only look at a small portion of it to get a general idea of what it contains before writing more complex queries.

##### **`LIMIT`**

If you recall earlier, we counted 100 customers in the `Customers` table. That's a lot of rows to show all at once in this notebook. Instead, let's only take a look at the first five rows of the data - that's enough for us to get an idea of what kind of data is in there. Here's how we'll do that:

```
SELECT *
FROM Customers
LIMIT 5
```

**Breakdown**

The only new part that we added in this query is the `LIMIT` clause at the end, followed by the number `5`. `LIMIT 5` says, **<em>"Only return the first five results from the query."</em>** The `LIMIT` clause accepts an integer number that specifies how many rows from the query results you want back. So if we instead wrote `LIMIT 10`, we would see the first 10 rows from the results.

##### **`OFFSET`**

Great! We can look at the first five customers. But what if we wanted to see the next five customers? What about the five after those? How can we specify that subset of rows in our query? That's where `OFFSET` comes into play.

Let's write a query using `OFFSET` to see the next five customers in our table:

```sql
SELECT *
FROM Customers
LIMIT 5 OFFSET 5
```

**Breakdown**

This query only adds one new part - the `OFFSET 5` after `LIMIT 5`. Here, `OFFSET 5` says, "Skip the first 5 rows and give me every row after that." Since we also have the `LIMIT 5` clause, the combination of the two says, "Skip the first 5 rows and give me the next 5 after." Like `ORDER BY`, the number your specify to `OFFSET` controls how many rows you skip.

Both `LIMIT` and `OFFSET` are typically come as the final part of your query, with `LIMIT` always coming before `OFFSET`.

##### **Action Item 1 - Using `LIMIT` and `OFFSET`**

Write a query that shows just the first five rows from the `Reservations` table. Include all of the columns.

<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT *
FROM Reservations
LIMIT 5
```

</details>

In [55]:
%%sql
SELECT *
FROM Reservations
LIMIT 5

   ReservationID  CustomerID                Date  PartySize
0              1          74 2018-06-01 15:30:00          6
1              2          67 2018-06-02 13:30:00          2
2              3          16 2018-06-04 08:00:00          4
3              4          87 2018-06-04 19:30:00          5
4              5          29 2018-06-06 13:00:00          1

##### **Action Item 2 - Using `LIMIT` and `OFFSET`**

Write a query that shows just the next five rows from the `Reservations` table. Include all of the columns. Order the results by `PartySize` in ascending order.

<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT *
FROM Reservations
ORDER BY PartySize
LIMIT 5 OFFSET 5
```

</details>

In [58]:
%%sql
SELECT *
FROM Reservations
ORDER BY PartySize ASC
LIMIT 5 OFFSET 5

   ReservationID  CustomerID                Date  PartySize
0             10          10 2018-06-14 09:00:00          1
1             43          26 2018-07-04 11:30:00          1
2             50          21 2018-07-08 13:30:00          1
3             71          34 2018-07-24 12:30:00          1
4             79          72 2018-08-03 10:00:00          1

**Great work! You have completed Lab 3!**

---

### **Data Aggregation and Ordering Basics - Comprehension Check**

Amazing job! You made it to the end of SQL 101. We have covered a lot of ground, from database theory to simple select queries, filtering your data, and summarizing it. You are ready to start analyzing data using SQL to generate insights! Let's do some review over what we've learned so far:

**1. What do we mean by aggregating data?**
<details>
    <summary>Click here to reveal the answer</summary>
    <p>Aggregating data is the process of gathering and summarizing large sets of data to produce a single, consolidated result.</p>
</details>

**2. What do aggregate functions do?**
<details>
    <summary>Click here to reveal the answer</summary>
    <p>Aggregate functions take in a column of values and performs a calculation on all of them, returning a single result.</p>
</details>

**3. When do we use the `GROUP BY` clause?**
<details>
    <summary>Click here to reveal the answer</summary>
    <p>We need to use <b>GROUP BY</b> when we want to aggregate (or summarize) our data by one or more categories that we specify.</p>
</details>

**4. What is the default sort order for the `ORDER BY` clause? Do we need to specify it in our queries?**
<details>
    <summary>Click here to reveal the answer</summary>
    <p>The default sort order in the <b>ORDER BY</b> clause is ascending order, or least to greatest. You do not need to specify the <b>ASC</b> keyword in your queries - it is optional.</p>
</details>

**5. Where in a query do we place the `LIMIT` and `OFFSET` clauses (when we use them)?**
<details>
    <summary>Click here to reveal the answer</summary>
    <p>The <b>LIMIT</b> and <b>OFFSET</b> clauses are both generally placed at the end of your queries.</p>
</details>

**6. What does it mean when we have a `NULL` value in our data?**
<details>
    <summary>Click here to reveal the answer</summary>
    <p>It means that the value at a particular point does not exist in the data set. It could be due to an error or it could be intentional, but that depends often on how the data was collected.</p>
</details>

## **Conclusion**

Well done! You have officially finished **SQL 101 - Intro to Databases and Querying**. You started off learning some of the theoretical background of databases, relational databases and SQL. Then you dove into the basics of querying, from selecting your data, to filtering and summarizing it. Finally, you learned how to sort your results based on your needs.

With the skills you have developed in this course, you can now start answering interesting and non-trivial questions about data in a single table. In the next course, **SQL 102 - Intermediate SQL Queries**, you will develop these skills even further and learn how to combine two or more tables to perform even more complex analyses.

If you like, there is an additional **Challenge** section at the end of this notebook that has some more complex/difficult queries for you to tackle. They are optional, but if you are wanting to test your skills, they are there. Good luck!

## More resources for further practice

- [SQL Bolt](https://sqlbolt.com/): The lessons here are a great introduction to SQL!
- [Mode](https://mode.com/sql-tutorial/): A comprehensive SQL tutorial from beginner all the way to advanced SQL. There's even a data analytics with SQL tutorial. This is a great resource to learn about SQL in depth and practice what you learn in their online database.
- [StrataScratch](https://platform.stratascratch.com/coding): Practice coding questions geared toward data analysts and data scientists. You can solve coding problems used by real companies for technical interviews using PostgresSQL, Python, R, or MySQL. It's free to sign up!
- [Codecademy - Free Learn SQL Course](https://www.codecademy.com/learn/learn-sql): Codecademy is another great resource to learn SQL as well as most other languages. There are a lot of free resources here that can help you learn SQL, Python, R, and many other languages.
- [Socratica SQL (YouTube)](https://www.youtube.com/watch?v=nWyyDHhTxYU&list=PLih4ch-U2DiBbMoFK4ML9faT3k3MM2UQY): This is a great playlist that will get you started learning SQL with one of the most popular relational databases - Postgres.
- [DB Fiddle](https://dbfiddle.uk/): This site is like a SQL scratch pad. You can use it to practice doing stuff like creating tables and inserting data into them, and all sorts of other stuff that you might not be able to do so freely in a live database. It's a sandbox, basically. Here are a couple of links to fiddles with some data in them to play with: [fiddle 1](https://dbfiddle.uk/?rdbms=postgres_13&fiddle=366b683701596d3f7459b0411c15acd1) and [fiddle 2](https://dbfiddle.uk/?rdbms=postgres_13&fiddle=dfffc1939f629d9286c55d732fb656c5).


And don't forget to keep your [SQL Cheatsheet](https://martinmarroyo.github.io/sqlcheatsheetandresources-coop/) handy!

## Challenge Section

This is an optional challenge section where you will write some more complicated queries to answer more nuanced questions based on the skills taught in this course.

### Challenge 1

**Difficulty Level: Easy-ish**

Write a query that shows the average price of all dishes that have cheese in them.

`Expected Output:`

| MeanPrice |
|-----------|
| 8.87      |

<br/>
<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT AVG(Price) AS MeanPrice
FROM Dishes
WHERE Description LIKE '%cheese%'
```

</details>

In [60]:
%%sql
SELECT Price,

BinderException: Binder Error: Referenced column "Menu" not found in FROM clause!

LINE 2: WHERE Menu = '%Cheese%'
              ^

### Challenge 2

**Difficulty Level: Medium**

Write a query that finds the top 5 states with the most customers who use a `.org` `Email` address.

`Expected Output:`

| State | TotalCustomers |
|-------|----------------|
| VA    | 5              |
| CA    | 5              |
| DC    | 3              |
| TX    | 3              |
| OH    | 2              |

<br/>
<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT State, COUNT(CustomerID) AS TotalCustomers
FROM Customers
WHERE Email LIKE '%.org'
GROUP BY State
ORDER BY TotalCustomers DESC
LIMIT 5

```

</details>

In [ ]:
%%sql

### Challenge 3

**Difficulty Level: Tricky**

Write a query that finds the total number of dishes as well as the average, minimum, and maximum price of a dish that has either `cheese` or `onion` in it. The query should show these metrics for each `Type` in the `Dishes` table. Order the output by the total number of dishes in descending order.

`Expected Output:`

| Type      | TotalDishes | LowestPrice | HighestPrice | MeanPrice |
|-----------|-------------|-------------|--------------|-----------|
| Main      | 8           | 7.00        | 9.99         | 8.87      |
| Appetizer | 1           | 7.00        | 7.00         | 7.00      |

<br/>
<details>
<summary>Click here to reveal answer</summary>

```sql
SELECT Type, COUNT(Type) AS TotalDishes, MIN(Price) AS LowestPrice, MAX(Price) AS HighestPrice, AVG(Price) AS MeanPrice
FROM Dishes
WHERE Description LIKE '%cheese%' OR Description LIKE '%onion%'
GROUP BY Type
ORDER BY TotalDishes DESC

```

</details>

In [ ]:
%%sql